---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: cicd 
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 32080
  - name: agent
    port: 50000
    targetPort: agent
    nodePort: 32081
